#resilience4j:
#    circuitbreaker:
#        instances:
#            weatherService:
#                automaticTransitionFromOpenToHalfOpenEnabled: true
#                eventConsumerBufferSize: 10
#                failureRateThreshold: 50
#                minimumNumberOfCalls: 5
#                permittedNumberOfCallsInHalfOpenState: 5
#                registerHealthIndicator: true
#                slidingWindowSize: 100
#                slidingWindowType: COUNT_BASED
#                waitDurationInOpenState: 100s
#server:
#    port: 8081
#timeout: 300000
#redis:
#    cache:
#        time-to-live: 30
#spring:
#    cache:
#        type: redis
#    data:
#        redis:
#            host: ${REDIS_PRIMARY_ENDPOINT}
#            port: ${REDIS_PORT}
#            timeout: 1000
#
#weather:
#    appid: ${APP_ID}
#    query:
#        map: '{''appId'':''&appId='',''city'':''&q='',''count'':''&cnt='',''units'':''&units=''}'
#    units:
#        api: https://api.openweathermap.org/data/2.5/forecast1?